kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: williamchanrico/debugapp
      tags:
        - latest
        - 0.1.0
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
