kind: pipeline
name: default
steps:
  - name: alpine
    image: plugins/docker
    settings:
      repo: williamchanrico/debugapp
      tags:
        - latest
        - 1.2.0
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

  - name: ubuntu
    image: plugins/docker
    settings:
      repo: williamchanrico/debugapp
      tags:
        - latest-ubuntu1804
        - 1.0.1-ubuntu1804
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      dockerfile: Dockerfile.ubuntu-1804
